// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemPlanilha.Data;

#nullable disable

namespace SistemPlanilha.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20250724195923_PermitirNulosEmPecasSubstituidas")]
    partial class PermitirNulosEmPecasSubstituidas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemPlanilha.Models.InventarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LicencaOffice")
                        .HasColumnType("bit");

                    b.Property<bool>("LicencaSO")
                        .HasColumnType("bit");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int?>("Patrimonio")
                        .HasColumnType("int");

                    b.Property<string>("PcName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrevisaoDevolucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Processador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Serial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SetorId")
                        .HasColumnType("int");

                    b.Property<int?>("SituacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Ssd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WinVerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.HasIndex("SetorId");

                    b.HasIndex("SituacaoId");

                    b.HasIndex("TipoId");

                    b.HasIndex("WinVerId");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("SistemPlanilha.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Office", (string)null);
                });

            modelBuilder.Entity("SistemPlanilha.Models.RelatorioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcoesRealizadas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<string>("ObservacoesAdicionais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PecasSubstituidas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProximaManutencao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelTecnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusManutencaoId")
                        .HasColumnType("int");

                    b.Property<string>("TempoEstimadoResolucao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoManutencao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.HasIndex("StatusManutencaoId");

                    b.ToTable("RelatoriosManutencao");
                });

            modelBuilder.Entity("SistemPlanilha.Models.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("SistemPlanilha.Models.Situacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Situacoes");
                });

            modelBuilder.Entity("SistemPlanilha.Models.StatusManutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusesManutencao");
                });

            modelBuilder.Entity("SistemPlanilha.Models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("SistemPlanilha.Models.WinVer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WinVer", (string)null);
                });

            modelBuilder.Entity("SistemPlanilha.Models.InventarioModel", b =>
                {
                    b.HasOne("SistemPlanilha.Models.Office", "Office")
                        .WithMany("Inventarios")
                        .HasForeignKey("OfficeId");

                    b.HasOne("SistemPlanilha.Models.Setor", "Setor")
                        .WithMany("Inventarios")
                        .HasForeignKey("SetorId");

                    b.HasOne("SistemPlanilha.Models.Situacao", "Situacao")
                        .WithMany("Inventarios")
                        .HasForeignKey("SituacaoId");

                    b.HasOne("SistemPlanilha.Models.Tipo", "Tipo")
                        .WithMany("Inventarios")
                        .HasForeignKey("TipoId");

                    b.HasOne("SistemPlanilha.Models.WinVer", "WinVer")
                        .WithMany("Inventarios")
                        .HasForeignKey("WinVerId");

                    b.Navigation("Office");

                    b.Navigation("Setor");

                    b.Navigation("Situacao");

                    b.Navigation("Tipo");

                    b.Navigation("WinVer");
                });

            modelBuilder.Entity("SistemPlanilha.Models.RelatorioModel", b =>
                {
                    b.HasOne("SistemPlanilha.Models.InventarioModel", "Inventario")
                        .WithMany()
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemPlanilha.Models.StatusManutencao", "StatusManutencao")
                        .WithMany("Relatorios")
                        .HasForeignKey("StatusManutencaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");

                    b.Navigation("StatusManutencao");
                });

            modelBuilder.Entity("SistemPlanilha.Models.Office", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("SistemPlanilha.Models.Setor", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("SistemPlanilha.Models.Situacao", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("SistemPlanilha.Models.StatusManutencao", b =>
                {
                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("SistemPlanilha.Models.Tipo", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("SistemPlanilha.Models.WinVer", b =>
                {
                    b.Navigation("Inventarios");
                });
#pragma warning restore 612, 618
        }
    }
}
